### ISSUE TITLE
Add if-not-set modifier

### ISSUE THREAD

**Issue by peterjaap** [semaio/Magento2-ConfigImportExport#80]
We want to start using this extension to push configuration to production by running `bin/magento config:data:import config/store production` in our pipeline.

We want to do this to add initial configuration for 3rd party extensions, much like the `<default>` tag in `config.xml` files.

However, we only want to do this when no initial value has been set, so basically we want to set a constraint, or an "if" modifier.

I was thinking about something like this;

```
path/to/config:
    if-not-set: true
    default:
        0: 1
```

Or

```
path/to/config:
    if: not-set
    default:
        0: 1
```

In the second case, the 'not-set' might in the future also be changed to something to introduce constraint based on either values already imported.
